import React from "react";
import PageCTA from "@/components/landing/PageCTA";
import { Link } from "react-router-dom";
const chatScreenshotImg = "/landing/chat.png";
const moodCheckinImg = "/landing/mood.png";
import { Button } from "@/components/ui/button";
import AnimatedSection from "@/components/landing/AnimatedSection";
import lunoImg from "@/assets/landing/luno.png";
import loloImg from "@/assets/landing/lolo.png";
import lumiImg from "@/assets/landing/lumi.png";
import lalaImg from "@/assets/landing/lala.png";
const parentDashboardImg = "/landing/kid-home.png";
const journeysIslandImg = "/landing/journey.png";
const familyIslandImg = "/landing/family.png";
import chatIslandImg from "@/assets/landing/island-chat-feature.png";
import storiesIslandImg from "@/assets/landing/island-stories-feature.png";
import storiesScreenshotImg from "@/assets/landing/stories-screenshot.png";
import chatBgTree from "@/assets/landing/chat-bg-tree.png";
import storiesBg from "@/assets/landing/stories-bg.png";
import journeysBg from "@/assets/landing/journeys-bg.png";
import familyBg from "@/assets/landing/family-bg.png";

const spacesDetail = [
  {
    emoji: "💬", title: "Chat", subtitle: "Curiosity & Conversation", tagline: "Where questions begin — and real learning follows.", character: "Luno", img: lunoImg, accentClass: "border-t-luno",
    aiLabel: "Responses generated by AI · Grounded in educational sources · Safety-filtered for your child's age",
    desc: "Your child asks, \"Why is the sky blue?\" — and gets a warm, patient answer at their level. Then a follow-up question. Then a little activity to see what stuck. No ads, no distractions, no content they shouldn't see.\n\nThe English National Curriculum (British curriculum) is already built into Luno's world — from Key Stage 1 through Key Stage 4. Science, maths, history, geography, and more — grounded in what your child is actually learning at school. Your child can revise for a test, explore beyond the textbook, or simply follow a question wherever it leads.\n\nA 5-year-old and a 13-year-old both get answers that meet them exactly where they are.",
    features: [
      "Questions met with patience, not overwhelm",
      "English National Curriculum built in — KS1 through KS4",
      "Adapts to every age — from early years to secondary school",
      "Little quizzes that feel like games, not tests",
      "Conversations can be saved — parents control what's kept",
    ],
  },
  {
    emoji: "📖", title: "Stories", subtitle: "Imagination & Creativity", tagline: "Where imagination leads.", character: "Lumi", img: lumiImg, accentClass: "border-t-lumi",
    aiLabel: "Stories co-created with AI · Content stays within age-appropriate boundaries · Parent-visible",
    desc: "\"What if the fox could fly?\" And just like that, the story changes.\n\nYour child doesn't just listen to stories here — they help shape them. They choose what happens next, name the characters, and decide if the adventure continues tomorrow.\n\nStories aren't rushed. They're built slowly, revisited when your child is ready.",
    features: [
      "Stories shaped by your child's imagination",
      "Characters and choices they create themselves",
      "Read aloud by Yoluno's AI narration",
      "Keepsakes you can print and keep forever",
      "A gentle space where stories can explore big feelings",
    ],
  },
  {
    emoji: "🧭", title: "Journeys", subtitle: "Habits & Gentle Growth", tagline: "Where small things grow quietly.", character: "Lolo", img: journeysIslandImg, accentClass: "border-t-lolo",
    aiLabel: "Prompts designed with child development guidance · AI-adapted to your child's pace",
    desc: "Your child might start a journey about bravery — and over a few days, through small prompts and reflections, begin to notice something new about themselves.\n\nProgress isn't measured in points. It's felt in moments.",
    features: [
      "Gentle routines that don't feel like homework",
      "Quiet reflections that build real awareness",
      "No scores, no streaks, no pressure",
      "Growth you'll notice at the dinner table",
      "Gently introduces words for feelings alongside everyday habits",
    ],
  },
  {
    emoji: "👨‍👩‍👧", title: "Family", subtitle: "Memory & Belonging", tagline: "Where your family stays close — even far away.", character: "Loti", img: familyIslandImg, accentClass: "border-t-lala",
    aiLabel: "Family-uploaded content only · AI does not generate voices or fabricate memories",
    desc: "One evening, your child asks: \"What was Grandma like when she was little?\"\n\nAnd they hear an answer — in a story you recorded, in your voice. Not generated, not invented. Your real words, saved here for when they matter.\n\nParents and family members record stories, upload photos, and add memories through the Parent Dashboard.",
    features: [
      "Family stories played back in familiar voices",
      "Photos and memories they can look through",
      "A sense of belonging that grows over time",
      "Everything stays private, within your family's world",
    ],
  },
];

export default function FeaturesPage() {
  return (
    <main className="pt-20">
      {/* Hero */}
      <section className="section-padding bg-background">
        <div className="container max-w-4xl text-center">
          <AnimatedSection>
            <p className="text-label mb-4">Features</p>
            <h1 className="font-heading text-4xl md:text-[48px] text-foreground mb-4">
              A World That Grows With Them
            </h1>
            <p className="font-body text-[17px] text-muted-foreground leading-relaxed mb-4 max-w-[560px] mx-auto">
              Four AI-guided spaces for curiosity, imagination, and gentle growth — in a closed environment you control. Designed for children ages 3 to 14.
            </p>
          </AnimatedSection>

          <AnimatedSection delay={0.2}>
            <div className="rounded-2xl overflow-hidden shadow-warm border border-border mb-8">
              <video autoPlay loop muted playsInline className="w-full h-auto">
                <source src="/videos/yoluno-world.mp4" type="video/mp4" />
              </video>
            </div>
          </AnimatedSection>

          <AnimatedSection delay={0.3}>
            <Button size="lg" asChild>
              <a href="#spaces">Explore the Spaces</a>
            </Button>
            <div className="ai-note mt-6 text-left max-w-xl mx-auto">
              Yoluno is powered by AI designed specifically for children — every response is safety-filtered, age-adapted, and visible to you in your Parent Dashboard.
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* Emotional Check-Ins */}
      <section className="py-[100px] px-6 md:px-12 bg-background">
        <div className="container max-w-[1200px]">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-12 items-center">
            <AnimatedSection>
              <div className="max-w-[520px]">
                <p className="font-body text-[12.5px] font-semibold uppercase tracking-[2.5px] text-primary mb-4">
                  Emotional Check-Ins
                </p>
                <h2 className="font-heading text-[36px] text-foreground mb-5 leading-tight">
                  Every Session Starts With Care
                </h2>
                <p className="font-body text-[16px] text-muted-foreground leading-[1.7] mb-4">
                  Before exploring, Luno asks your child how they're feeling. Their answer shapes what happens next.
                </p>
                <p className="font-body text-[16px] text-muted-foreground leading-[1.7] mb-4">
                  If your child feels happy or excited, Luno matches their energy — jumping into stories, challenges, or questions. If your child feels sad, worried, or tired, Luno responds gently — offering a comforting story, a look through family photos, or a quiet space to talk. Your child chooses what feels right.
                </p>
                <p className="font-body text-[16px] text-muted-foreground leading-[1.7] mb-6">
                  Every check-in is visible in your Parent Dashboard, so you can see how your child is feeling over time — without having to ask.
                </p>
                <div className="border-l-[3px] border-primary bg-secondary p-4 pl-5">
                  <p className="font-body text-[13.5px] text-muted-foreground">
                    Mood check-ins designed with child wellbeing guidance · Responses adapt in real time · All check-in data visible to parents
                  </p>
                </div>
              </div>
            </AnimatedSection>

            <AnimatedSection delay={0.2} className="flex justify-center">
              <div className="max-w-[480px] w-full rounded-[20px] overflow-hidden shadow-[0_8px_32px_rgba(42,41,38,0.08)]">
                <img src={moodCheckinImg} alt="Luno mood check-in screen showing emotion options" className="w-full h-auto" loading="lazy" />
              </div>
            </AnimatedSection>
          </div>
        </div>
      </section>

      {/* Section Intro */}
      <section id="spaces" className="section-padding bg-secondary">
        <div className="container max-w-3xl text-center">
          <AnimatedSection>
            <h2 className="font-heading text-3xl text-foreground mb-4">Four Spaces. One World.</h2>
            <p className="font-body text-[17px] text-muted-foreground leading-relaxed max-w-[560px] mx-auto">
              Each space exists for a different kind of curiosity. Your child moves between them freely — exploring what interests them, at the pace that feels right.
            </p>
          </AnimatedSection>
        </div>
      </section>

      {/* Four Spaces */}
      {spacesDetail.map((space, i) => (
        <React.Fragment key={space.title}>
        <section
          className={`py-12 md:py-16 px-6 md:px-12 ${i % 2 === 0 ? "bg-background" : "bg-secondary"} relative overflow-hidden`}
        >
          {space.title === "Chat" && (
            <div className="absolute inset-0 pointer-events-none">
              <img src={chatBgTree} alt="" className="absolute right-0 top-1/2 -translate-y-1/2 h-full w-auto object-contain opacity-[0.15]" />
            </div>
          )}
          {space.title === "Stories" && (
            <div className="absolute inset-0 pointer-events-none">
              <img src={storiesBg} alt="" className="absolute left-0 top-1/2 -translate-y-1/2 h-full w-auto object-contain opacity-[0.15]" />
            </div>
          )}
          {space.title === "Journeys" && (
            <div className="absolute inset-0 pointer-events-none">
              <img src={journeysBg} alt="" className="absolute right-0 top-1/2 -translate-y-1/2 h-full w-auto object-contain opacity-[0.15]" />
            </div>
          )}
          {space.title === "Family" && (
            <div className="absolute inset-0 pointer-events-none">
              <img src={familyBg} alt="" className="absolute left-0 top-1/2 -translate-y-1/2 h-full w-auto object-contain opacity-[0.15]" />
            </div>
          )}
          <div className="container max-w-5xl relative z-10">
            <AnimatedSection>
              <div className={`grid md:grid-cols-2 gap-12 items-center`}>
                <div className={`${i % 2 !== 0 ? "md:order-2" : ""} bg-card/90 backdrop-blur-sm rounded-2xl p-8 border border-border shadow-warm`}>
                  <span className={`inline-flex items-center gap-2 font-body font-semibold text-sm uppercase tracking-widest px-5 py-2 rounded-full mb-3 ${space.title === "Stories" ? "bg-[#7C6FAE] text-white" : space.title === "Journeys" ? "bg-[#D94F3B] text-white" : space.title === "Family" ? "bg-[#E8B630] text-white" : "bg-primary text-primary-foreground"}`}>{space.emoji} {space.title}</span>
                  <p className="font-body text-sm font-medium text-muted-foreground uppercase tracking-wide mb-1">{space.subtitle}</p>
                  <h2 className="font-heading text-3xl text-foreground mb-4">{space.tagline}</h2>
                  
                  <div className="ai-note mb-4 text-xs">{space.aiLabel}</div>
                  
                  {space.desc.split("\n\n").map((paragraph, pi) => (
                    <p key={pi} className="font-body text-foreground text-[17px] leading-[1.7] mb-4">{paragraph}</p>
                  ))}
                  <ul className="space-y-3 mb-6">
                    {space.features.map((f) => (
                      <li key={f} className="flex items-center gap-3 font-body text-foreground text-[15px]">
                        <span className="text-primary">✓</span> {f}
                      </li>
                    ))}
                  </ul>
                </div>
                <div className={`flex flex-col items-center justify-center gap-4 ${i % 2 !== 0 ? "md:order-1" : ""}`}>
                  {space.title === "Family" ? (
                    <>
                      <div className="relative">
                        <div className="hidden md:block absolute -right-5 -bottom-5 w-full h-full rounded-3xl" style={{ backgroundColor: "#FDF6E8", zIndex: 0 }} />
                        <div
                          className="relative max-w-[520px] rounded-[20px] overflow-hidden"
                          style={{ border: "2px solid #D4A843", boxShadow: "0 12px 40px rgba(212,168,67,0.15)", zIndex: 1 }}
                        >
                          <img src={familyIslandImg} alt="Family - My Family Tree" className="w-full object-cover" />
                        </div>
                      </div>
                      <div className="flex items-center justify-center gap-2 mt-3">
                        <div className="w-4 h-4 rounded-full" style={{ backgroundColor: "#FDF6E8" }} />
                        <p className="font-body text-[13px]" style={{ color: "#9B978E" }}>Guided by {space.character}</p>
                      </div>
                    </>
                  ) : space.title === "Journeys" ? (
                    <>
                      <div className="relative">
                        <div className="hidden md:block absolute -right-5 -bottom-5 w-full h-full rounded-3xl" style={{ backgroundColor: "#FDEAE6", zIndex: 0 }} />
                        <div
                          className="relative max-w-[520px] rounded-[20px] overflow-hidden"
                          style={{ border: "2px solid #E8B0A4", boxShadow: "0 12px 40px rgba(217,79,59,0.15)", zIndex: 1 }}
                        >
                          <img src={journeysIslandImg} alt="Journeys - Being Brave progress screen" className="w-full object-cover" />
                        </div>
                      </div>
                      <div className="flex items-center justify-center gap-2 mt-3">
                        <div className="w-4 h-4 rounded-full" style={{ backgroundColor: "#FDEAE6" }} />
                        <p className="font-body text-[13px]" style={{ color: "#9B978E" }}>Guided by {space.character}</p>
                      </div>
                    </>
                  ) : space.title === "Chat" ? (
                    <>
                      <div className="relative">
                        {/* Decorative offset rectangle - desktop only */}
                        <div className="hidden md:block absolute -right-5 -bottom-5 w-full h-full rounded-3xl" style={{ backgroundColor: "#E8F6F4", zIndex: 0 }} />
                        <div
                          className="relative max-w-[520px] rounded-[20px] overflow-hidden bg-white"
                          style={{ border: "1px solid #E8E6E1", boxShadow: "0 12px 40px rgba(42,41,38,0.10)", zIndex: 1 }}
                        >
                          <img src={chatScreenshotImg} alt="Chat with Luno" className="w-full object-cover" />
                        </div>
                      </div>
                      <div className="flex items-center justify-center gap-2 mt-3">
                        <div className="w-4 h-4 rounded-full flex-shrink-0" style={{ backgroundColor: "#E8F6F4" }} />
                        <p className="font-body" style={{ fontSize: 13, color: "#9B978E" }}>Guided by Luno</p>
                      </div>
                    </>
                   ) : space.title === "Stories" ? (
                    <>
                       <div className="relative">
                         <div className="hidden md:block absolute -right-5 -bottom-5 w-full h-full rounded-3xl" style={{ backgroundColor: "#E8E0F0", zIndex: 0 }} />
                         <div
                           className="relative max-w-[520px] rounded-[20px] overflow-hidden"
                           style={{ border: "2px solid #C4B5D9", boxShadow: "0 12px 40px rgba(124,111,174,0.18)", zIndex: 1 }}
                         >
                           <img src={storiesScreenshotImg} alt="Stories - leto and the Giggle-Snorting Goats" className="w-full object-cover" />
                         </div>
                      </div>
                      <div className="flex items-center justify-center gap-2 mt-3">
                        <div className="w-4 h-4 rounded-full" style={{ backgroundColor: "#F3EEF8" }} />
                        <p className="font-body text-[13px]" style={{ color: "#9B978E" }}>Guided by {space.character}</p>
                      </div>
                    </>
                  ) : (
                    <>
                      <img src={space.img} alt={space.character} className="w-48 h-48 object-contain drop-shadow-lg character-bloom" />
                      <p className="font-heading text-center text-foreground">Guided by {space.character}</p>
                    </>
                  )}
                </div>
              </div>
            </AnimatedSection>
           </div>
         </section>
         {space.title === "Chat" && (
           <>
           {/* Curriculum Callout */}
           <section style={{ backgroundColor: "#F5F3EE", padding: "60px 0" }}>
             <div className="container" style={{ maxWidth: 900 }}>
               <AnimatedSection>
                 <div className="grid grid-cols-1 md:grid-cols-5 gap-10 items-start">
                   <div className="md:col-span-3">
                     <p className="font-body mb-3" style={{ fontSize: "12.5px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "2.5px", color: "#3ECDC6" }}>CURRICULUM ALIGNED</p>
                     <h2 className="font-heading mb-5" style={{ fontSize: 30, color: "#2A2926", lineHeight: 1.3 }}>Not just educational. Aligned to what they're actually learning.</h2>
                     <p className="font-body mb-4" style={{ fontSize: 16, color: "#6B675E", lineHeight: 1.75 }}>
                       The English National Curriculum is built into Yoluno — from Reception through Year 11. When your child asks Luno about forces and motion, they get an answer grounded in the same framework their teacher uses. When they explore the Tudors, the depth matches their Key Stage.
                     </p>
                     <p className="font-body mb-6" style={{ fontSize: 16, color: "#6B675E", lineHeight: 1.75 }}>
                       This isn't a search engine giving a random answer. It's structured knowledge, adapted to your child's age, delivered with patience.
                     </p>
                     <div className="flex flex-wrap gap-2 mb-4">
                       {["Science", "Maths", "History", "Geography", "English", "Computing"].map((subj) => (
                         <span key={subj} className="font-body" style={{ backgroundColor: "#FFFFFF", border: "1px solid #E8E6E1", borderRadius: 20, padding: "6px 16px", fontSize: 13, color: "#6B675E" }}>{subj}</span>
                       ))}
                     </div>
                     <p className="font-body" style={{ fontSize: 13, color: "#9B978E" }}>More curricula coming soon — including UAE MOE framework and US Common Core.</p>
                   </div>
                   <div className="md:col-span-2">
                     <div className="bg-white rounded-2xl p-7" style={{ border: "1px solid #E8E6E1", boxShadow: "0 4px 16px rgba(42,41,38,0.06)" }}>
                       <p className="font-body font-semibold mb-4" style={{ fontSize: 14, color: "#2A2926" }}>Example: Year 4 Science</p>
                       <div className="flex flex-col gap-3">
                         <div className="ml-auto" style={{ backgroundColor: "#E8F6F4", borderRadius: 12, padding: "12px 16px", maxWidth: "80%" }}>
                           <p className="font-body" style={{ fontSize: 13, color: "#2A2926" }}>Why does ice melt?</p>
                         </div>
                         <div className="flex items-start gap-2" style={{ maxWidth: "90%" }}>
                           <div className="flex-shrink-0 w-5 h-5 rounded-full flex items-center justify-center text-white font-body" style={{ backgroundColor: "#3ECDC6", fontSize: 10, fontWeight: 700 }}>L</div>
                           <div style={{ backgroundColor: "#FFFFFF", border: "1px solid #E8E6E1", borderRadius: 12, padding: "12px 16px" }}>
                             <p className="font-body" style={{ fontSize: 13, color: "#2A2926", lineHeight: 1.6 }}>Great question! When ice gets warmer than 0°C, the molecules start moving faster and break apart from their solid shape. That's melting! What do you think happens if you put salt on ice?</p>
                           </div>
                         </div>
                       </div>
                       <p className="font-body mt-3" style={{ fontSize: 11, color: "#9B978E" }}>Aligned to KS2 — States of Matter</p>
                     </div>
                   </div>
                 </div>
               </AnimatedSection>
             </div>
           </section>

           {/* Multilingual Callout */}
           <section style={{ backgroundColor: "#E8F6F4", padding: "60px 0" }}>
             <div className="container" style={{ maxWidth: 800 }}>
               <AnimatedSection>
                 <p className="font-body text-center mb-3" style={{ fontSize: "12.5px", fontWeight: 600, textTransform: "uppercase", letterSpacing: "2.5px", color: "#3ECDC6" }}>MULTILINGUAL</p>
                 <h2 className="font-heading text-center mb-5" style={{ fontSize: 32, color: "#2A2926" }}>One World. Every Language.</h2>
                 <p className="font-body text-center mb-8" style={{ fontSize: 16, color: "#2A2926", lineHeight: 1.75 }}>
                   Yoluno works in over 20 languages — including English, Arabic, French, Mandarin Chinese, Italian, Spanish, Hindi, Urdu, and more. Your child can chat with Luno in Arabic, build a story with Lumi in French, or explore a journey with Lolo in English — all within the same account. Switch languages anytime. Every language gets the same safety filters, the same age adaptation, and the same parent visibility.
                 </p>
                 <div className="flex flex-wrap justify-center gap-3">
                   {["English", "العربية", "Français", "中文", "Italiano", "Español", "हिन्दी", "اردو", "Deutsch", "Português", "日本語", "한국어"].map((lang) => (
                     <span key={lang} className="font-body" style={{ backgroundColor: "#FFFFFF", borderRadius: 20, padding: "6px 16px", fontSize: 13, color: "#6B675E" }}>{lang}</span>
                   ))}
                 </div>
               </AnimatedSection>
             </div>
           </section>
           </>
         )}
        </React.Fragment>
      ))}

      {/* Warm Handoff */}
      <section className="section-padding bg-secondary">
        <div className="container max-w-3xl text-center">
          <AnimatedSection>
            <h2 className="font-heading text-3xl text-foreground mb-6">
              Every Space Is Guided by Care — and Governed by You.
            </h2>
            <p className="font-body text-[17px] text-muted-foreground leading-relaxed mb-8 max-w-[560px] mx-auto">
              You set the boundaries. You choose what's allowed. Yoluno operates within those limits — gently, automatically, and without exception.
            </p>
            <Button variant="outline" size="lg" asChild>
              <Link to="/for-parents">See How Parents Stay in Control →</Link>
            </Button>
          </AnimatedSection>
        </div>
      </section>

      {/* What If Something Isn't Right */}
      <section className="section-padding bg-background">
        <div className="container max-w-3xl">
          <AnimatedSection>
            <div className="bg-card rounded-2xl p-10 md:p-14 border border-border">
              <h2 className="font-heading text-2xl md:text-3xl text-foreground mb-6">What If Something Isn't Right?</h2>
              <p className="font-body text-muted-foreground text-[17px] leading-[1.7] mb-8">
                We built Yoluno knowing that no system is perfect — and that your trust depends on what happens when something unexpected comes up.
              </p>
              <div className="space-y-6">
                {[
                  { title: "If the AI gets something wrong:", text: "Every response your child sees can be reviewed in your Parent Dashboard. If something doesn't look right, you can flag it — and our team reviews flagged content within 24 hours." },
                  { title: "If your child is upset:", text: "Yoluno's guides gently redirect when a conversation becomes distressing. If a child needs real human support, Yoluno pauses and encourages them to talk to a parent — it does not act as a counsellor." },
                  { title: "If you disagree with how a topic was handled:", text: "You can adjust topic boundaries at any time. You can also block specific subjects entirely. Yoluno's AI operates within the limits you set — and those limits update immediately." },
                ].map((item) => (
                  <div key={item.title}>
                    <h3 className="font-heading text-lg text-foreground mb-2">{item.title}</h3>
                    <p className="font-body text-muted-foreground leading-[1.7]">{item.text}</p>
                  </div>
                ))}
              </div>
              <p className="font-heading text-foreground italic mt-8 text-lg">
                We'd rather be honest about edges than pretend they don't exist.
              </p>
            </div>
          </AnimatedSection>
        </div>
      </section>

      {/* Quote */}
      <section className="section-padding bg-secondary">
        <div className="container max-w-3xl text-center">
          <AnimatedSection>
            <blockquote className="bg-card rounded-2xl p-8 border border-border">
              <p className="font-heading text-xl text-foreground">
                At Yoluno, we believe children don't need more content — they need presence, patience, and possibility.
              </p>
            </blockquote>
          </AnimatedSection>
        </div>
      </section>

      {/* Parent Dashboard Bridge */}
      <section className="section-padding bg-background">
        <div className="container max-w-3xl text-center">
          <AnimatedSection>
            <p className="text-label mb-3">For Parents and Educators</p>
            <h2 className="font-heading text-3xl text-foreground mb-4">
              Oversight and Insight on Your Terms
            </h2>
            <p className="font-body text-[17px] text-muted-foreground leading-relaxed max-w-[560px] mx-auto mb-8">
              Your Parent Dashboard gives you full visibility — conversation summaries, topics explored, time spent, and anything flagged. You choose how closely you follow along.
            </p>
            <div className="rounded-2xl overflow-hidden shadow-warm border border-border max-w-2xl mx-auto">
              <img src={parentDashboardImg} alt="Yoluno kids home screen" className="w-full h-auto" loading="lazy" />
            </div>
            <Button variant="outline" size="lg" className="mt-8" asChild>
              <Link to="/for-parents">Learn More About Parent Controls →</Link>
            </Button>
          </AnimatedSection>
        </div>
      </section>

      <PageCTA
        heading="The Technology and AI powered product you'd actually want your child to use."
        subtitle="Four spaces. 20+ languages. Every conversation visible to you. See it for yourself."
      />
    </main>
  );
}
